# Étape 1 : image Node avec Angular CLI
FROM node:18-alpine

# Dossier de travail dans le container
WORKDIR /app

# Copier package.json + package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier tout le code source
COPY . .

# Exposer le port Angular dev server
EXPOSE 4200

# Commande pour lancer le serveur Angular en mode dev
CMD ["npm", "start"]
