FROM node:18-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production
COPY . .
RUN npm run build -- --configuration production --output-path=dist --no-prerender

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
# Vérifie que le fichier existe avant de copier
RUN test -f /app/nginx.conf && echo "nginx.conf found" || echo "nginx.conf not found"
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]